### ISSUE TITLE
Add support for receiving control messages

### ISSUE THREAD

**Issue by zanebeckwith** [xaptum/xaptum_client#3]

**Comment by iguberman** [comment]
What do you mean?

**Comment by zanebeckwith** [comment]
Ah, I'm sorry, I was moving quickly and didn't understand the code well enough! I didn't see that it does support control messages. I logged this issue as a TODO for myself, before I'd read the code well enough.

My mistake. I'll close this issue.

**Comment by iguberman** [comment]
Ah, I see, thought it was meant to be something specific...  sorry for lack of comments on my part.
